export const data = [
  {
    Sno: 1,
    Departmentoftheitem: "Beverages",
    Itemnumber: 123456,
    Description: "Bru Filter coffee",
    SecondDescription: "filter coffee",
    Qty: "100g",
    Avgcost: 90,
    MRP: 150,
    Priceyoucharge: 100,
    Pricewithtax: 118,
    Instock: 10,
  },
  {
    Sno: 2,
    Departmentoftheitem: "Beverages",
    Itemnumber: 123457,
    Description: "weikfield coffee",
    SecondDescription: "chocolate coffee",
    Qty: "100g",
    Avgcost: 95,
    MRP: 350,
    Priceyoucharge: 100,
    Pricewithtax: 110,
    Instock: 30,
  },
  {
    Sno: 3,
    Departmentoftheitem: "Beverages",
    Itemnumber: 123458,
    Description: "Bru Filter coffee",
    SecondDescription: "instant coffee",
    Qty: "150g",
    Avgcost: 145,
    MRP: 200,
    Priceyoucharge: 100,
    Pricewithtax: 170,
    Instock: 78,
  },
  // {
  //   'Sno': 4,
  //   'Department of the item': 'Beverages',
  //   Itemnumber: 123459,
  //   Description: 'Tata Tea',
  //   '2nd description': 'Agni Tea',
  //   Qty: '100g',
  //   'Avg cost': 144,
  //   'Price you charge': 164,
  //   'Price with tax': 170,
  //   'In stock': 76
  // },
  // {
  //   'Sno': 5,
  //   'Department of the item': 'Beverages',
  //   Itemnumber: 123460,
  //   Description: '3 Roses',
  //   '2nd description': 'Dust',
  //   Qty: '100g',
  //   'Avg cost': 165,
  //   'Price you charge': 185,
  //   'Price with tax': 190,
  //   'In stock': 45
  // },
  // {
  //   'Sno': 6,
  //   'Department of the item': 'Beverages',
  //   Itemnumber: 123461,
  //   Description: 'AVT',
  //   '2nd description': 'Premium',
  //   Qty: '200g',
  //   'Avg cost': 340,
  //   'Price you charge': 360,
  //   'Price with tax': 370,
  //   'In stock': 33
  // },
  // {
  //   'Sno': 7,
  //   'Department of the item': 'Dairy',
  //   Itemnumber: 123462,
  //   Description: 'Milky mist',
  //   '2nd description': 'Processed',
  //   Qty: '200g',
  //   'Avg cost': 48,
  //   'Price you charge': 58,
  //   'Price with tax': 65,
  //   'In stock': 22
  // },
  // {
  //   'Sno': 8,
  //   'Department of the item': 'Dairy',
  //   Itemnumber: 123463,
  //   Description: 'Britannia ',
  //   '2nd description': 'Box',
  //   Qty: '200g',
  //   'Avg cost': 34,
  //   'Price you charge': 44,
  //   'Price with tax': 50,
  //   'In stock': 22
  // },
  // {
  //   'Sno': 9,
  //   'Department of the item': 'Dairy',
  //   Itemnumber: 123464,
  //   Description: 'Aavin',
  //   '2nd description': 'green aavin',
  //   Qty: '500ml',
  //   'Avg cost': 35,
  //   'Price you charge': 55,
  //   'Price with tax': 60,
  //   'In stock': 33
  // },
  // {
  //   'Sno': 10,
  //   'Department of the item': 'Dairy',
  //   Itemnumber: 123465,
  //   Description: 'Arogya',
  //   '2nd description': 'Extra Fat',
  //   Qty: '500ml',
  //   'Avg cost': 65,
  //   'Price you charge': 75,
  //   'Price with tax': 80,
  //   'In stock': 44
  // },
  // {
  //   'Sno': 11,
  //   'Department of the item': 'Dairy',
  //   Itemnumber: 123466,
  //   Description: 'Dodla Dairy',
  //   '2nd description': 'Premium',
  //   Qty: '500ml',
  //   'Avg cost': 35,
  //   'Price you charge': 45,
  //   'Price with tax': 55,
  //   'In stock': 55
  // },
  // {
  //   'Sno': 12,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123467,
  //   Description: 'Arun Ice',
  //   '2nd description': 'choco bar',
  //   Qty: '50ml',
  //   'Avg cost': 45,
  //   'Price you charge': 65,
  //   'Price with tax': 70,
  //   'In stock': 66
  // },
  // {
  //   'Sno': 13,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123468,
  //   Description: 'Arun Ice',
  //   '2nd description': 'fiest',
  //   Qty: '50ml',
  //   'Avg cost': 65,
  //   'Price you charge': 75,
  //   'Price with tax': 80,
  //   'In stock': 77
  // },
  // {
  //   'Sno': 14,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123469,
  //   Description: 'Iceberg',
  //   '2nd description': 'choco bar',
  //   Qty: '100ml',
  //   'Avg cost': 23,
  //   'Price you charge': 33,
  //   'Price with tax': 40,
  //   'In stock': 88
  // },
  // {
  //   'Sno': 15,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123470,
  //   Description: 'iceberg',
  //   '2nd description': 'fiest',
  //   Qty: '75ml',
  //   'Avg cost': 65,
  //   'Price you charge': 75,
  //   'Price with tax': 80,
  //   'In stock': 99
  // },
  // {
  //   'Sno': 16,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123471,
  //   Description: 'kwality',
  //   '2nd description': 'milky bart',
  //   Qty: '50ml',
  //   'Avg cost': 87,
  //   'Price you charge': 97,
  //   'Price with tax': 110,
  //   'In stock': 76
  // },
  // {
  //   'Sno': 17,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123472,
  //   Description: 'kwality',
  //   '2nd description': 'mango bar',
  //   Qty: '100ml',
  //   'Avg cost': 78,
  //   'Price you charge': 88,
  //   'Price with tax': 90,
  //   'In stock': 43
  // },
  // {
  //   'Sno': 18,
  //   'Department of the item': 'Frozen Foods',
  //   Itemnumber: 123473,
  //   Description: 'mashroom',
  //   '2nd description': 'fresh ',
  //   Qty: '250g',
  //   'Avg cost': 64,
  //   'Price you charge': 74,
  //   'Price with tax': 80,
  //   'In stock': 121
  // },
  // {
  //   'Sno': 19,
  //   'Department of the item': 'Personal Care',
  //   Itemnumber: 123474,
  //   Description: 'Dove Shampoo',
  //   '2nd description': 'dandruf clean',
  //   Qty: '180ml',
  //   'Avg cost': 43,
  //   'Price you charge': 63,
  //   'Price with tax': 70,
  //   'In stock': 23
  // },
  // {
  //   'Sno': 20,
  //   'Department of the item': 'Personal Care',
  //   Itemnumber: 123475,
  //   Description: 'Head and shoulder',
  //   '2nd description': 'silk and shine',
  //   Qty: '180ml',
  //   'Avg cost': 35,
  //   'Price you charge': 55,
  //   'Price with tax': 60,
  //   'In stock': 34
  // }
];
