export const data = [
  {
    Sno: 1,
    Departmentoftheitem: "Beverages",
    Itemnumber: 123456,
    Description: "Bru Filter coffee",
    SecondDescription: "filter coffee",
    Qty: "100g",
    Avgcost: 90,
    MRP: 150,
    Priceyoucharge: 100,
    Pricewithtax: 118,
    Instock: 10,
  },
  {
    Sno: 2,
    Departmentoftheitem: "Beverages",
    Itemnumber: 123457,
    Description: "weikfield coffee",
    SecondDescription: "chocolate coffee",
    Qty: "100g",
    Avgcost: 95,
    MRP: 350,
    Priceyoucharge: 100,
    Pricewithtax: 110,
    Instock: 30,
  },
  {
    Sno: 3,
    Departmentoftheitem: "Beverages",
    Itemnumber: 123458,
    Description: "Bru Filter coffee",
    SecondDescription: "instant coffee",
    Qty: "150g",
    Avgcost: 145,
    MRP: 200,
    Priceyoucharge: 100,
    Pricewithtax: 170,
    Instock: 78,
  },
];
